export enum IpcEventNamesEnum {
    REQUIRE_AUTH = 'REQUIRE_AUTH',
    CONNECT_ERROR = 'REQUIRE_AUTH',
    CONNECTED = 'CONNECTED',
    GET_CONNECTION_STATUS = 'GET_CONNECTION_STATUS',
    GET_CONFIG = 'GET_CONFIG',
}
