export enum IpcEventNamesEnum {
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  CONNECT_ERROR = 'REQUIRE_AUTH',
  CONNECTED = 'CONNECTED',
  GET_CONNECTION_STATUS = 'GET_CONNECTION_STATUS',
  GET_APP_INFO = 'GET_APP_INFO',
  GET_CONFIG = 'GET_CONFIG',
  STATE_CHANGE = 'STATE_CHANGE',
  COMMANDS_LOG_CHANGE = 'COMMANDS_LOG_CHANGE',
  GET_COMMANDS_LOG = 'GET_COMMANDS_LOG',
}
