export enum IpcEventNamesEnum {
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  CONNECT_ERROR = 'REQUIRE_AUTH',
  CONNECTED = 'CONNECTED',
  GET_CONNECTION_STATUS = 'GET_CONNECTION_STATUS',
  GET_CONFIG = 'GET_CONFIG',
}
